site_name: SIXSA

nav:
  - Home:
    - Welcome: index.md
    - Examples:
        - examples/basic_fit.ipynb
    - API Reference:
      - Solver: api/solver.md
      - Embedding: api/embedding.md
      - Plotting: api/plotting.md

theme:
  name: material
  features:
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
#    - content.code.select
#    - navigation.instant
    - navigation.tabs
    - navigation.sections
#    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.top
#    - toc.integrate
    - header.autohide
    - navigation.expand


  favicon: logo/logo_small.svg
  logo: logo/logo_small.svg
  icon:
    repo: fontawesome/brands/github

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue

      #primary: cyan
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      #primary: cyan
      primary: blue
      accent: blue

      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search
  - mkdocs-jupyter:
      include_source: true
      ignore_h1_titles: true
      execute: false
      include_requirejs: true
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          import:
            - https://docs.python.org/3/objects.inv
            - https://docs.astropy.org/en/latest/objects.inv
            - https://samreay.github.io/ChainConsumer/objects.inv
            - https://python.arviz.org/en/latest/objects.inv
            - https://sbi.readthedocs.io/en/latest/objects.inv
            - https://matplotlib.org/objects.inv
          options:
            members_order: alphabetical
            docstring_section_style: table
            docstring_style: google
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            modernize_annotations: true

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

repo_url: https://github.com/renecotyfanboy/bsixsa
repo_name: bsixsa

extra_css:
  - css/material.css
  - css/mkdocstrings.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

watch: [mkdocs.yml, src/bsixsa]